# Imports

In [29]:
import numpy as np
import torch
print(torch.__version__)

1.9.0+cu102


## Conversions with Numpy

In [6]:
## lets see how torch tensors looks like
x1 = [[1,1],[2,2]]
print("Type of data :{}".format(type(x1)))
print(x1)
x1 = np.array(x1)
print("Type of data :{}".format(type(x1)))
print(x1)

Type of data :<class 'list'>
[[1, 1], [2, 2]]
Type of data :<class 'numpy.ndarray'>
[[1 1]
 [2 2]]


In [7]:
## converting numpy array to tensor
x_tensor = torch.tensor(x1)
print("Type of data :{}".format(type(x_tensor)))
print(x_tensor)

Type of data :<class 'torch.Tensor'>
tensor([[1, 1],
        [2, 2]])


In [8]:
x1 =np.array([[2,2],[2,2]])
x_tensor

tensor([[1, 1],
        [2, 2]])

In [9]:
x_tensor = torch.Tensor(x1)
print("Type of data :{}".format(type(x_tensor)))
print(x_tensor)

Type of data :<class 'torch.Tensor'>
tensor([[2., 2.],
        [2., 2.]])


In [10]:
x1 =np.array([[1,2],[1,2]])
x_tensor

tensor([[2., 2.],
        [2., 2.]])

In [11]:
x_tensor = torch.from_numpy(x1)
print("Type of data :{}".format(type(x_tensor)))
print(x_tensor)

Type of data :<class 'torch.Tensor'>
tensor([[1, 2],
        [1, 2]])


In [12]:
x1 =np.array([[2,2],[2,2]])
x_tensor

tensor([[1, 2],
        [1, 2]])

## Generating tensors

In [20]:
## generating tensors
zero_t = torch.zeros((2,2))
print(zero_t)
one_t = torch.ones((2,2))
print(one_t)
rand_t = torch.rand(2,2)
print(rand_t)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.1928, 0.3161],
        [0.2537, 0.1133]])


In [21]:
print(one_t + rand_t)

tensor([[1.1928, 1.3161],
        [1.2537, 1.1133]])


In [22]:
print(one_t*rand_t)

tensor([[0.1928, 0.3161],
        [0.2537, 0.1133]])


## Array manipulations

In [24]:
array1 = torch.tensor([1,2,4])
array2 = torch.tensor([2,3,4])
print(torch.dot(array1,array2))

tensor(24)


In [28]:
array1 = torch.tensor([1,2,4]).reshape(1,-1)
print(array1.shape)
array2 = torch.tensor([2,3,4]).reshape(-1,1)
print(array2.shape)
print(torch.matmul(array2,array1))

torch.Size([1, 3])
torch.Size([3, 1])
tensor([[ 2,  4,  8],
        [ 3,  6, 12],
        [ 4,  8, 16]])
